  "use client"
  import { DriverProvider } from "./useContext/DriverContext";
  import "./globals.css";

  const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body
        >
          <DriverProvider>
            {children}
          </DriverProvider>
        </body>
      </html>
    );
  }
